server:
  port: 8087
  servlet:
    context-path: /api/v1/courses

spring:
  application:
    name: course-service
  datasource:
    url: "jdbc:mysql://localhost:3306/course_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true